// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:b2530b88-618a-4585-9fa1-93ff462fd9f4',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ewlpalymepatientapp-hosting-mobilehub-513083560',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2pjtyy4b1t3ut.cloudfront.net',
    'aws_mobile_analytics_app_id': 'e8d4894c401e457b8903796d92c6a7d5',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '6db66456-ebb7-493b-b2ab-f9a9b72f5d1d',
    'aws_project_name': 'ewlpa-lyme-patient-app-2018-07-19-19-11-34',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'ewlpalymepatientapp-mobilehub-513083560',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_3btuLcQyx',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '49hocnstkh9hdt3c5dh5ve5vij',
}

export default awsmobile;
