// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"pkwkuo40u9","name":"Pets","description":"","endpoint":"https://pkwkuo40u9.execute-api.us-west-1.amazonaws.com/Development","region":"us-west-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:2f2af98c-9860-4394-9744-94830b1f1689',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awslymepatientapp-hosting-mobilehub-510683692',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dr85nsb637xsp.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-1',
    'aws_dynamodb_table_schemas': [{"tableName":"awslymepatientapp-mobilehub-510683692-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-west-1","hashKey":"userId","rangeKey":"petId"}],
    'aws_mobile_analytics_app_id': 'a84db7bbd91c477ebd0c192087e4adcd',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '840cbc1b-a7a6-491e-bf31-09e49597187e',
    'aws_project_name': 'aws-lyme-patient-app-2018-07-20-11-02-27',
    'aws_project_region': 'us-west-1',
    'aws_resource_bucket_name': 'awslymepatientapp-deployments-mobilehub-510683692',
    'aws_resource_name_prefix': 'awslymepatientapp-mobilehub-510683692',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'awslymepatientapp-userfiles-mobilehub-510683692',
    'aws_user_files_s3_bucket_region': 'us-west-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_5wiBOapJO',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5oth9saq5b2tpabl79ouenl538',
}

export default awsmobile;
